---
- name: deploy vms accorss hosts
  hosts: simulator07
  vars_files:
    - vars/main.yml
  tasks:
  - debug: var=playbook_dir
  - template: src="templates/hosts.json" dest="/opt/hosts.json" force=yes
    template: src="templates/hosts.json" dest="{{ playbook_dir }}/../hosts_inventory/{{ inventory_hostname }}" force=yes
    delegate_to: "localhost"
  - fetch: src=/opt/hosts.json dest="/opt/simulator/hosts_inventory/{{ inventory_hostname }}.json" flat=yes
  - file: path=/opt/templates/vmnode-config/ state=directory recurse=yes
  - name: copy necessary file 
    copy: src="templates/{{ item }}" dest="/opt/{{ item }}"
    with_items:
      - functions.rc
      - vars.rc
      - setup-host.sh
      - deploy-vms.sh
  - name: copy VMs xml template
    template: src="templates/vmnode-config/{{ item }}" dest="/opt/templates/vmnode-config/{{ item }}" force=yes
    with_items:
      - cinder.openstackci.local.xml
      - infra.openstackci.local.xml
      - logging.openstackci.local.xml
      - network.openstackci.local.xml
      - nova_compute.openstackci.local.xml
      - swift.openstackci.local.xml
  - name: setup host prior to deplying vms
    shell: bash setup-host.sh
    args:
      chdir: /opt
  - name: deploy vms
    shell: bash deploy-vms.sh
    args:
      chdir: /opt
