---
- name: deploy vms accorss hosts
  hosts: simulator03
  vars_files:
    - vars/main.yml
  tasks:
  - template: src="templates/hosts.json" dest="/opt/hosts.json" force=yes
  - file: path=/opt/templates/vmnode-config/ state=directory recurse=yes
  - name: copy necessary file 
    copy: src="templates/{{ item }}" dest="/opt/{{ item }}"
    with_items:
      - functions.rc
      - vars.rc
      - setup-host.sh
      - deploy-vms.sh
  - name: copy VMs xml template
    template: src="templates/vmnode-config/{{ item }}" dest="/opt/templates/vmnode-config/{{ item }}" force=yes
    with_items:
      - cinder.openstackci.local.xml
      - infra.openstackci.local.xml
      - logging.openstackci.local.xml
      - network.openstackci.local.xml
      - nova_compute.openstackci.local.xml
      - swift.openstackci.local.xml
  - name: setup host prior to deplying vms
    shell: bash setup-host.sh
    args:
      chdir: /opt
#  - name: copy right vm configurations to hosts
  - name: deploy vms
    shell: bash deploy-vms.sh
    args:
      chdir: /opt
