---
- name: partition a disk to host the VMs
  hosts: simulator
  vars_files:
    - vars/main.yml
  tasks:
  - name: make sure parted is installed
    package:
      name: parted
      state: present
  - name: "Partition disk"
    shell: |
      if [ -b /dev/{{ use_disk }} ]
      then
        if [ ! -b /dev/{{ use_disk }}1 ] 
        then
          parted --script /dev/{{ use_disk }} mklabel gpt
          parted --align optimal --script /dev/{{ use_disk }} mkpart kvm ext4 0% 100%
        fi
      fi
  - name: "make filesystem on the partition"
    filesystem:
      dev: '/dev/{{ use_disk }}1'
      force: yes
      fstype: ext4

  - name: "Ensure mount directory exists"
    file:
      path: '/var/lib/libvirt/images/'
      state: directory

  - name: "Mount additional disk"
    mount:
      name: '/var/lib/libvirt/images/'
      fstype: 'ext4'
      passno: '0'
      src: '/dev/{{ use_disk }}1'
      state: 'mounted'
